# Generated by Django 5.2.7 on 2025-10-16 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_reserva_paquete_reserva_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='Transferencia', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('numero_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Verificado', 'Verificado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, help_text='Comentario del administrador (si es rechazado o revisado)', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='condominio.usuario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='condominio.reserva')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
