# Generated by Django 5.2.7 on 2025-10-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_reservaservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='es_personalizado',
            field=models.BooleanField(default=False, help_text='Indica si el paquete fue creado por el usuario'),
        ),
    ]
