# Generated by Django 5.2.7 on 2025-10-30 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_alter_proveedor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('registration_id', models.CharField(max_length=512, unique=True, verbose_name='token_registro')),
                ('tipo_dispositivo', models.CharField(blank=True, max_length=20, null=True, verbose_name='tipo_dispositivo')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Si el token está activo para recibir notificaciones', verbose_name='activo')),
                ('ultima_vez', models.DateTimeField(auto_now=True, verbose_name='ultima_vez')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_fcm', to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo FCM',
                'verbose_name_plural': 'Dispositivos FCM',
                'abstract': False,
            },
        ),
    ]
