# Generated by Django 5.2.7 on 2025-11-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_fcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ticket_nuevo', 'Ticket Nuevo'), ('ticket_respondido', 'Ticket Respondido'), ('ticket_cerrado', 'Ticket Cerrado'), ('campana_marketing', 'Campaña Marketing'), ('promocion', 'Promoción'), ('recordatorio', 'Recordatorio'), ('sistema', 'Sistema')], max_length=50),
        ),
        migrations.CreateModel(
            name='CampanaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre interno de la campaña para identificarla', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del objetivo de la campaña', null=True)),
                ('titulo', models.CharField(help_text='Título de la notificación push (visible en el dispositivo)', max_length=100)),
                ('cuerpo', models.TextField(help_text='Cuerpo del mensaje de la notificación')),
                ('tipo_notificacion', models.CharField(choices=[('ticket_nuevo', 'Ticket Nuevo'), ('ticket_respondido', 'Ticket Respondido'), ('ticket_cerrado', 'Ticket Cerrado'), ('campana_marketing', 'Campaña Marketing'), ('promocion', 'Promoción'), ('recordatorio', 'Recordatorio'), ('sistema', 'Sistema')], default='campana_marketing', help_text='Tipo de notificación que se creará', max_length=50)),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Datos adicionales JSON (deep link, imagen_url, accion, etc.)')),
                ('tipo_audiencia', models.CharField(choices=[('TODOS', 'Todos los usuarios'), ('SEGMENTO', 'Segmento específico'), ('USUARIOS', 'Lista de usuarios')], default='TODOS', help_text='Tipo de segmentación de audiencia', max_length=20)),
                ('segmento_filtros', models.JSONField(blank=True, default=dict, help_text='Filtros Django ORM JSON: {"rol__nombre": "Cliente", "num_viajes__gte": 5}')),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Fecha y hora para envío automático. Si es null y enviar_inmediatamente=False, no se envía', null=True)),
                ('enviar_inmediatamente', models.BooleanField(default=False, help_text='Si es True, ignora fecha_programada y envía al activar')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', help_text='Estado actual de la campaña', max_length=20)),
                ('fecha_enviada', models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó el envío', null=True)),
                ('total_destinatarios', models.IntegerField(default=0, help_text='Número total de usuarios objetivo calculado')),
                ('total_enviados', models.IntegerField(default=0, help_text='Número de notificaciones enviadas exitosamente')),
                ('total_leidos', models.IntegerField(default=0, help_text='Número de notificaciones leídas (se actualiza posteriormente)')),
                ('total_errores', models.IntegerField(default=0, help_text='Número de envíos fallidos')),
                ('enviado_por', models.ForeignKey(blank=True, help_text='Usuario administrador que activó el envío', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_enviadas', to='condominio.usuario')),
                ('usuarios_objetivo', models.ManyToManyField(blank=True, help_text="Usuarios específicos (solo si tipo_audiencia='USUARIOS')", related_name='campanas_notificacion', to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Campaña de Notificación',
                'verbose_name_plural': 'Campañas de Notificación',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='condominio__estado_10107a_idx'), models.Index(fields=['tipo_audiencia'], name='condominio__tipo_au_38aa12_idx')],
            },
        ),
    ]
