# Generated by Django 5.2.7 on 2025-11-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_paquete_es_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad o región específica', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='departamento',
            field=models.CharField(choices=[('La Paz', 'La Paz'), ('Santa Cruz', 'Santa Cruz'), ('Cochabamba', 'Cochabamba'), ('Potosí', 'Potosí'), ('Oruro', 'Oruro'), ('Tarija', 'Tarija'), ('Chuquisaca', 'Chuquisaca'), ('Beni', 'Beni'), ('Pando', 'Pando'), ('Multi-departamental', 'Multi-departamental')], default='La Paz', help_text='Departamento principal del paquete turístico', max_length=50),
        ),
        migrations.AddField(
            model_name='paquete',
            name='tipo_destino',
            field=models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural'), ('Natural', 'Natural'), ('Histórico', 'Histórico'), ('Mixto', 'Mixto')], default='Mixto', help_text='Tipo de destino del paquete', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad específica del servicio', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='departamento',
            field=models.CharField(choices=[('La Paz', 'La Paz'), ('Santa Cruz', 'Santa Cruz'), ('Cochabamba', 'Cochabamba'), ('Potosí', 'Potosí'), ('Oruro', 'Oruro'), ('Tarija', 'Tarija'), ('Chuquisaca', 'Chuquisaca'), ('Beni', 'Beni'), ('Pando', 'Pando')], default='La Paz', help_text='Departamento donde se realiza el servicio', max_length=50),
        ),
    ]
