# Generated by Django 5.2.7 on 2025-11-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_alter_notificacion_tipo_campananotificacion'),
        ('condominio', '0007_paquete_ciudad_paquete_departamento_and_more'),
    ]

    operations = [
    ]
