# Generated by Django 5.2.7 on 2025-11-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0008_merge_20251102_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmdevice',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ticket_nuevo', 'Ticket Nuevo'), ('ticket_respondido', 'Ticket Respondido'), ('ticket_cerrado', 'Ticket Cerrado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad principal del paquete turístico', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento principal del paquete turístico', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='tipo_destino',
            field=models.CharField(blank=True, choices=[('Cultural', 'Cultural'), ('Natural', 'Natural'), ('Aventura', 'Aventura'), ('Rural', 'Rural'), ('Urbano', 'Urbano')], help_text='Tipo de destino turístico', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde se realiza el servicio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento donde se realiza el servicio', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CampanaNotificacion',
        ),
        migrations.DeleteModel(
            name='FCMDevice',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
