# Generated by Django 5.2.7 on 2025-11-02 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0009_remove_fcmdevice_usuario_remove_proveedor_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno de la campaña', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción interna (no se envía)')),
                ('titulo', models.CharField(help_text='Título que verá el usuario (máx 100 caracteres)', max_length=100)),
                ('cuerpo', models.TextField(help_text='Mensaje que verá el usuario (máx 500 caracteres)', max_length=500)),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Datos adicionales para la app (acción, URL, etc.)')),
                ('tipo_notificacion', models.CharField(choices=[('informativa', 'Informativa'), ('promocional', 'Promocional'), ('urgente', 'Urgente'), ('campana_marketing', 'Campaña Marketing'), ('actualizacion_sistema', 'Actualización Sistema')], default='informativa', max_length=50)),
                ('tipo_audiencia', models.CharField(choices=[('TODOS', 'Todos los usuarios'), ('USUARIOS', 'Usuarios específicos'), ('SEGMENTO', 'Segmento por filtros'), ('ROL', 'Por rol')], default='TODOS', max_length=20)),
                ('segmento_filtros', models.JSONField(blank=True, default=dict, help_text='Filtros de segmentación (rol, num_viajes, etc.)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('ERROR', 'Error')], default='BORRADOR', max_length=20)),
                ('enviar_inmediatamente', models.BooleanField(default=True, help_text='Si es True, se envía al activar. Si es False, usar fecha_programada')),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Fecha y hora de envío programado', null=True)),
                ('fecha_enviada', models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó el envío', null=True)),
                ('total_destinatarios', models.IntegerField(default=0, help_text='Número de destinatarios objetivo')),
                ('total_enviados', models.IntegerField(default=0, help_text='Notificaciones enviadas exitosamente')),
                ('total_errores', models.IntegerField(default=0, help_text='Notificaciones con error')),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='Detalles completos del envío')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuarios_objetivo', models.ManyToManyField(blank=True, help_text='Usuarios específicos (si tipo_audiencia=USUARIOS)', related_name='campanas_notificacion', to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Campaña de Notificación',
                'verbose_name_plural': 'Campañas de Notificación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.TextField(help_text='Token FCM único del dispositivo', unique=True)),
                ('tipo_dispositivo', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', help_text='Tipo de dispositivo', max_length=20)),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo (ej: "Celular de Juan")', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para recibir notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el token')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_fcm', to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo FCM',
                'verbose_name_plural': 'Dispositivos FCM',
                'ordering': ['-ultima_vez'],
            },
        ),
    ]
