# Generated by Django 5.2.7 on 2025-11-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0011_proveedor_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
